# Default values for croc-hunter.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

serviceType: ClusterIP
servicePort: 80
containerPort: 8080
component: "croc-hunter"
replicas: 3
image: "dfsacr.azurecr.io/campbelldgunn/croc-hunter"
imageTag: "latest"
imagePullPolicy: "Always"
cpu: "10m"
memory: "128Mi"
nodeSelector:
  os: linux
# Ingress settings
ingress:
  enabled: true
  hostname: croc-hunter.ddns.net
  annotations:
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
  tls: true
# PodDisruptionBudget
pdb:
  enabled: false
  minAvailable: 2
